### ISSUE TITLE
[BUG] Error using from_single_file

### ISSUE THREAD

**Issue by Subcode** [PRIS-CV/DemoFusion#21]
Traceback (most recent call last):
  File "/home/user/Repositories/run.py", line 6, in <module>
    pipe = DemoFusionSDXLPipeline.from_single_file(model_ckpt)
  File "/home/user/Repositories/env/lib/python3.10/site-packages/diffusers/loaders.py", line 2268, in from_single_file
    raise ValueError(f"Unhandled pipeline class: {pipeline_name}")
ValueError: Unhandled pipeline class: DemoFusionSDXLPipeline

**Comment by Laidawang** [comment]
`    pipe_base = StableDiffusionXLPipeline.from_single_file('/data2/home/srchen/PROJECT/github/DemoFusion/models/realvisxlV20_v20Bakedvae.safetensors',
                                                    torch_dtype=torch.float16
    )
    pipe = DemoFusionSDXLPipeline( 
        vae = pipe_base.vae,
        text_encoder = pipe_base.text_encoder,
        text_encoder_2 = pipe_base.text_encoder_2,
        tokenizer = pipe_base.tokenizer,
        tokenizer_2 = pipe_base.tokenizer_2,
        unet = pipe_base.unet,
        scheduler = pipe_base.scheduler,
        force_zeros_for_empty_prompt = pipe_base.force_zeros_for_empty_prompt,
        )`
      try this

**Comment by deroberon** [comment]
I can help on this one. This is because the diffusers python library, in the "single_file.py" (where implements "from_single_file" function) expects that the class name contains the word "StableDiffusion", as you can see here: 

https://github.com/huggingface/diffusers/blob/2d94c7838e273c40920ffd6d24d724357add7f2d/src/diffusers/loaders/single_file.py#L207C15-L207C30

and  the class implemented here in pipeline_demodifusion_sdxl.py is called "DemoFusionSDXLPipeline" and for not contain the "StableDiffusion" word in the name, the load function fails.

Just changing the name of the class for something like: "DemoFusionStableDiffusionSDXLPipeline" will solve the problem.
