### ISSUE TITLE
low-resolution image to high resolution image: image_lr shape and range

### ISSUE THREAD

**Issue by HanLiii** [PRIS-CV/DemoFusion#51]

**Comment by HanLiii** [comment]
In addition, when I try to launch DemoFusion Image2Image by python gradio_demo_img2img.py, it will give back type error:

Traceback (most recent call last):
  File "/home/hli358/anaconda3/envs/demofusion/lib/python3.9/site-packages/pydantic/_internal/_typing_extra.py", line 264, in eval_type_backport
    return typing._eval_type(  # type: ignore
  File "/home/hli358/anaconda3/envs/demofusion/lib/python3.9/typing.py", line 292, in _eval_type
    return t._evaluate(globalns, localns, recursive_guard)
  File "/home/hli358/anaconda3/envs/demofusion/lib/python3.9/typing.py", line 554, in _evaluate
    eval(self.__forward_code__, globalns, localns),
  File "<string>", line 1, in <module>
TypeError: unsupported operand type(s) for |: 'ModelMetaclass' and 'NoneType'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/hli358/han/DemoFusion/gradio_demo_img2img.py", line 4, in <module>
    from gradio_imageslider import ImageSlider
  File "/home/hli358/anaconda3/envs/demofusion/lib/python3.9/site-packages/gradio_imageslider/__init__.py", line 1, in <module>
    from .imageslider import ImageSlider
  File "/home/hli358/anaconda3/envs/demofusion/lib/python3.9/site-packages/gradio_imageslider/imageslider.py", line 21, in <module>
    class SliderData(GradioRootModel):
  File "/home/hli358/anaconda3/envs/demofusion/lib/python3.9/site-packages/pydantic/_internal/_model_construction.py", line 200, in __new__
    set_model_fields(cls, bases, config_wrapper, types_namespace)
  File "/home/hli358/anaconda3/envs/demofusion/lib/python3.9/site-packages/pydantic/_internal/_model_construction.py", line 469, in set_model_fields
    fields, class_vars = collect_model_fields(cls, bases, config_wrapper, types_namespace, typevars_map=typevars_map)
  File "/home/hli358/anaconda3/envs/demofusion/lib/python3.9/site-packages/pydantic/_internal/_fields.py", line 132, in collect_model_fields
    type_hints = get_cls_type_hints_lenient(cls, types_namespace)
  File "/home/hli358/anaconda3/envs/demofusion/lib/python3.9/site-packages/pydantic/_internal/_typing_extra.py", line 228, in get_cls_type_hints_lenient
    hints[name] = eval_type_lenient(value, globalns, localns)
  File "/home/hli358/anaconda3/envs/demofusion/lib/python3.9/site-packages/pydantic/_internal/_typing_extra.py", line 240, in eval_type_lenient
    return eval_type_backport(value, globalns, localns)
  File "/home/hli358/anaconda3/envs/demofusion/lib/python3.9/site-packages/pydantic/_internal/_typing_extra.py", line 273, in eval_type_backport
    raise TypeError(
TypeError: You have a type annotation 'Union[Tuple[FileData | None, FileData | None], None]' which makes use of newer typing features than are supported in your version of Python. To handle this error, you should either remove the use of new syntax or install the `eval_type_backport` package.
